# Generated by Django 4.1.7 on 2023-11-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelage', '0002_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('R', 'Reviewed'), ('N', 'Not reviwed'), ('E', 'Error'), ('A', 'Acepted')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
