# Generated by Django 4.1.7 on 2023-11-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelage', '0003_website_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
