# Generated by Django 4.1.7 on 2023-11-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelage', '0005_user_car_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellPhone',
            fields=[
                ('number', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
