# Generated by Django 4.1.7 on 2023-11-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelage', '0006_cellphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cell_phone',
            field=models.ManyToManyField(to='modelage.cellphone', verbose_name='los números de contacto'),
        ),
    ]
